### ISSUE TITLE
Existence of readiness constraints

### ISSUE THREAD

**Issue by RonAsis** [RonAsis/Wsep202#14]
Existence of readiness constraints
For each readiness constraint, we need to show how it is guaranteed: by construction, or by acceptance scenarios:

1. At least one system administrator. The administrator must be a subscriber (undergoing a registration process).
2. A shop owner or a store manager must be a subscriber.
3. Integrity. For example: a. b) A purchase process cannot be successfully completed without paying the required amount for the product c. The seller cannot receive payment as a result of a successful buying process.
4. An active (un-closed) store must have at least one store.

Existence of readiness constraints
For each readiness constraint, we need to show how it is guaranteed: by construction, or by acceptance scenarios:

1. At least one system administrator. The administrator must be a subscriber (undergoing a registration process).
2. A shop owner or a store manager must be a subscriber.
3. Integrity. For example: a. b) A purchase process cannot be successfully completed without paying the required amount for the product c. The seller cannot receive payment as a result of a successful buying process.
4. An active (un-closed) store must have at least one store.
5. The store must be defined as: a .Buy types (purchase) and discount types. B. Purchase and discount policies.
6. The buyer has at most a single buyer for the store. A shopping cart that is purchased consists of a collection of all of its shopping baskets.
7. A shopping cart (guest or subscription) is the sole and exclusive property of any other user.
8. Requires at least one link to a collection system.
9. Requires at least one supply system link.

**Comment by KseniaDr** [comment]
For each correctness constraint we’ll show how we will ensure its existence:
1.	At least one system administrator. Administrator must be registered (meaning he has been through registration process) – as shown in the class diagram the class TradingSystem holds at least one SystemAdministrator class (1..*).
In addition as shown in the class diagram we used the Decorator design pattern in order to ensure that the SystemAdministrator must be a RegisteredUser.

2.	A store owner or store manager must be a registered – as shown in the class diagram we used the Decorator design pattern in order to ensure that the Owner and StoreManager must be a RegisteredUser.

3.	Integrity – for example we will show scenario a:
	(I) Buyers cannot be charged for transactions that they didn’t make, nor (II) can they be charged a different amount than what they are supposed to be charged –  
scenario (I)
	1. The buyer enters to the system.
	2. The buyer searches for the product that he wants.
	3. The buyer finds the product that costs x$ and adds it to the cart.
	4. The buyer clicks on the cart and clicks on ‘pay’.
	5. The buyer clicks ‘cancel’ or ‘exit’. 
        Input (before clicking pay): the product that the buyer chose (clicked on).
        Output: the system does not charge the buyer.
scenario (II)
	1. The buyer enters to the system.
	2. The buyer searches for the product that he wants.
	3. The buyer finds the product that costs x$ and adds it to the cart.
	4. The buyer clicks on the cart and clicks on ‘pay’.
	5. The buyer inserts the necessary information, including credit card details. 
	6. The buyer ensures that the shown amount is x$ and clicks ‘confirm’.
        Input (after clicking pay): the buyer inserts his credit card details. 
        Output: the system will return a confirmation message that his credit card will be charged x$.

4.	An active (non-closed) store must have at least one owner – as shown in the class diagram the class Store holds at least one Owner class (1..*). 

5.	The buyer has a single shopping bag for each store. A buyer's shopping cart contains a collection of all his shopping bag – as shown in the class diagram the classes Store, Guest and ShoppingBag have a trinary relation of 1 to 1, for each store and guest there is only one shopping bag. 
In addition, the buyers shopping cart is represented as a list of shopping bags in the Guest class.

6.	Buyer's shopping cart (guest or registered) is his exclusive property and is not alterable by any other user – as we said in the previous constraint (constraint number 5), the shopping cart is represented as a list of shopping bags in the Guest class. For that reason, no user can change another user’s shopping cart.

7.	There needs to be at least one connection to the charging system – as shown in the class diagram the class TradingSystem holds a 1 to 1 connection to ExternalServiceHandler class. The ExternalServiceHandler holds a 1 to 1 connection to the ChargeSystem. 

8.	There needs to be at least one connection to the suppling system – as shown in the class diagram the class TradingSystem holds a 1 to 1 connection to ExternalServiceHandler class. The ExternalServiceHandler holds a 1 to 1 connection to the SupplySystem. 

[גרסה0- משימה ה.docx](https://github.com/RonAsis/Wsep202/files/4340014/0-.docx)

**Comment by RonAsis** [comment]
1. At least one system administrator. Administrator must be registered (meaning he has been through registration process) – as shown in the class diagram the class TradingSystemManagement holds at least one Administrator class (1..*). In addition as shown in the class diagram we used the Decorator design pattern in order to ensure that the Administrator must be a BuyerRegisteredUser.

- Need to change it . TradingSystemManagement  don't need to holds Administrator.
replace with : 
1. At least one system administrator. Administrator must be registered (meaning he has been through registration process) – as shown in functional requirement : System 1.1 we initial the system with the Administrator.
In addition we prevent from any administrator to remove any a another administrator.
This invariant happened to through all the program.

**Comment by RonAsis** [comment]
add headers to the pages  : h1 , h2 , h3

**Comment by KseniaDr** [comment]
done
